### ISSUE TITLE
Expose bucket sizes for Kv

### ISSUE THREAD

**Issue by aricart** [nats-io/nats-architecture-and-design#164] opened 2022-09-29 15:53 UTC
## Overview

[expose bucket size as `bytes`](https://github.com/nats-io/nats-architecture-and-design/pull/159)

## Clients and Tools

 - [x] CLI @ripienaar
 - [ ] Go @piotrpio
 - [ ] Java @scottf
 - [ ] JavaScript @aricart
 - [ ] .Net @scottf
 - [ ] C @kozlovic
 - [ ] Python @wallyqs
 - [ ] Ruby @wallyqs
 - [ ] Rust @Jarema @caspervonb
   
## Other Tasks

 - [ ] docs.nats.io updated @jnmoyne
 - [ ] Update ADR to `Implemented`
 - [ ] Update client features spreadsheet

Client authors please update with your progress. If you open issues in your own repositories as a result of this request, please link them to this one by pasting the issue URL in a comment or main issue description.

**Comment by kozlovic** [comment] 2022-09-29 15:54
I think that @scottf just created #163

**Comment by scottf** [comment] 2022-09-29 15:59
Closing - duplicate of #163

**Closed by scottf** 2022-09-29 15:59 UTC
Labels: enhancement, client
